### ISSUE TITLE
Error: Call to undefined method DatabaseStatementBase::fetchArray() in uc_discounts_get_discounts_for_order() 

### ISSUE THREAD

**Issue by nattywebdev** [backdrop-contrib/uc_discounts#15]
When trying to add an item to the cart that has a discount applied, I am seeing the following error after the message '[product] added to your shopping cart':

`Error: Call to undefined method DatabaseStatementBase::fetchArray() in uc_discounts_get_discounts_for_order() (line 1637 of /<my-site>/web/modules/uc_discounts/uc_discounts.module).`

Is this a bug or perhaps something I've done wrong?

I'm using Backdrop 1.25.1 and ubercart 1.x-3.14.1 with uc_discounts 1.x-2.0.5.

**Comment by nattywebdev** [comment]
On further investigation I found this appears to be caused by setting Max uses per user to anything other than the default of 0. I had it set to 1. Reset to 0 and the error goes away.

**Comment by bugfolder** [comment]
Glad there's a workaround, but that's still a bug (that function doesn't exist in Backdrop). Will look into it.

**Comment by argiepiano** [comment]
I believe `fetchArray` should be replaced by `fetchAssoc()`, but I haven't tested this

**Comment by bugfolder** [comment]
Actually, `fetchField()` will be cleaner. I'm working on this now, made the fix, just testing it.
