### ISSUE TITLE
Setting 'Show messages about discounts in discounts checkout pane' not being saved

### ISSUE THREAD

**Issue by nattywebdev** [backdrop-contrib/uc_discounts#16]
In Checkout Settings (admin/store/settings/checkout) under the Discount codes pane settings, when I check:
Show messages about discounts in discounts checkout pane

and save, this setting is not saved.

Is this a bug or am I doing something unusual?

**Comment by bugfolder** [comment]
It's a bug, PR to come shortly.

**Comment by bugfolder** [comment]
@nattywebdev, could you test the PR?

**Comment by nattywebdev** [comment]
@bugfolder loaded new version and yes, the checkbox is now saved. However, I don't see anything different on the customer checkout display. Am I missing something?
Correction: I DO now see a checkout pane, so this PR appears to have fixed my issue. Many thanks for a speedy response!

**Comment by nattywebdev** [comment]
I'm now seeing a new error (notice) message but will log this as a separate issue.
It's a php notice:
Notice: Undefined index: line_item_id in uc_discounts_uc_order() (line 268 of /<myroot>/web/modules/uc_discounts/uc_discounts.module).

Logged as  #19

**Comment by bugfolder** [comment]
Yeah, I'm finding new things as I fix the old ones!
