### ISSUE TITLE
Add a feature that optional display of the discount in the Cart Contents pane of Checkout

### ISSUE THREAD

**Issue by nattywebdev** [backdrop-contrib/uc_discounts#24]
Add a feature to UC Discounts that makes showing the discount in the Cart Contents pane of Checkout optional via a checkbox in the settings. 

Currently the discount can be optionally shown in the Payment method pane (or not) and it would make sense in some cases to be able to display it there and not display it in the Cart Contents pane.

This request is with reference to the discussion on 
https://github.com/backdrop-contrib/uc_pma/issues/2

**Comment by bugfolder** [comment]
@nattywebdev, I've committed this option to HEAD (along with some other fixes). Would you be able to try it out and confirm that it works for you (and doesn't create any new problems)?

**Comment by nattywebdev** [comment]
I can confirm that the option to display discount in the Cart Contents pane of Checkout is shown and works. When checked, the discount appears in the Cart Contents pane and when unchecked it does not.

The display in the Payment Method pane is not affected by this, as expected.


@bugfolder Thank you so much for adding this feature!

Option to show discounts in cart contents pane checkable:

![Screenshot from 2023-09-15 13-04-35](https://github.com/backdrop-contrib/uc_discounts/assets/54537636/aa98c189-68c3-4f54-a753-00c915ef5093)

Cart contents display with option checked:

![Screenshot from 2023-09-15 13-03-19](https://github.com/backdrop-contrib/uc_discounts/assets/54537636/fb884da0-d297-4436-a597-c996038ecc7b)

Cart contents display with option unchecked:

![Screenshot from 2023-09-15 13-02-32](https://github.com/backdrop-contrib/uc_discounts/assets/54537636/af4e1368-fbe9-465f-b66f-92ece21d5241)
