### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/uc_discounts#4]
@bugfolder, did the latest release get tagged wrong accidentally (it backs up from 1.x-2.x to 1.x-1.x)?

 - https://github.com/backdrop-contrib/uc_discounts/releases

Noticed after taking a quick gander from this forum issue:

 - https://forum.backdropcms.org/forum/ubercart-discounts-unable-add-discount

**Comment by bugfolder** [comment]
Yup, good catch. Will fix immediately.

Robert
